### PR TITLE
Make test classes conform to an interface

### PR DESCRIPTION
**Pull request by chimosky**
This makes it easier to implement more tests in the future without having to worry about how they're called and creating a new dict item for each newly created class.

@44yu5h @drLite35 kindly test and review.

**__N/B:__** I haven't tested this.

### CODE REVIEW

**Comment by 44yu5h** [comment]
There were multiple runtime errors in this PR so I pushed a commit with some changes fixing them in a new branch [fix/pr/8](https://github.com/44yu5h/rpi_control_center/tree/fix/pr/8). You can pull from there.

Thanks

**Comment by chimosky** [comment]
Looked at c8b14b4, it'll be great to share the errors thrown.

**Comment by 44yu5h** [comment]
There were issues that required minor changes. You can quick-run them if you have sugar installed.

From what I remember there were errors of missing `import` keyword, some inconsistencies with icon names, `radiobutton_cb()` returned multiple errors, and some inconsistencies across the names in `rp_list` and what was being used in `activity.py`

**Comment by chimosky** [comment]
I don't have any of the dependencies needed so I can't test it without getting lots of errors, please test and paste the error so I can see.

I understand that the errors are minor, but I can only agree with your changes if I see the errors.

**Comment by 44yu5h** [comment]
I fixed the issues you pointed out in the review. Thanks
I'm sorry for not getting back to you sooner. Below are the errors and the changes I made:

---
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 179, in main
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Activities/rpi_control_center/activity.py", line 10
    from rp_tests.rp_audio RP_AUDIO
                           ^^^^^^^^
SyntaxError: invalid syntax
```
Fixed [L5-11](https://github.com/44yu5h/rpi_control_center/commit/088f4ed372fa5492cb9b02b5c0806008fe6ce979#:~:text=%23%20from%20gpio%20import,%2C%20name)

---
After fixing this:
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 179, in main
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Activities/rpi_control_center/activity.py", line 10, in <module>
    module = importlib.import_module('rp_tests.' + name.lower())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'rp_tests.rp_cam'
```
Renamed `rp_camera.py` to `rp_cam.py`

---
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 230, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 59, in create_activity_instance
    activity = constructor(handle)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Activities/rpi_control_center/activity.py", line 36, in __init__
    button.set_tooltip(tooltips[name])
                       ~~~~~~~~^^^^^^
KeyError: 'RP_GPIO'
```
Fixed [here](https://github.com/44yu5h/rpi_control_center/commit/088f4ed372fa5492cb9b02b5c0806008fe6ce979#:~:text=%5D-,tooltips%20%3D%20%7B,%7D,-gpio%20%3D%20%5B)

---
```
1722136015.938407 WARNING root: No icon with the name RP_GPIO was found in the theme.
1722136015.938530 WARNING root: No icon with the name RP_GPIO was found in the theme.
1722136015.938590 WARNING root: No icon with the name RP_I2C was found in the theme.
1722136015.938625 WARNING root: No icon with the name RP_I2C was found in the theme.
1722136015.938658 WARNING root: No icon with the name RP_SPI was found in the theme.
1722136015.938687 WARNING root: No icon with the name RP_SPI was found in the theme.
1722136015.938724 WARNING root: No icon with the name RP_CAM was found in the theme.
1722136015.938746 WARNING root: No icon with the name RP_CAM was found in the theme.
1722136015.938770 WARNING root: No icon with the name RP_AUDIO was found in the theme.
1722136015.938792 WARNING root: No icon with the name RP_AUDIO was found in the theme.
1722136015.938815 WARNING root: No icon with the name RP_SETTINGS was found in the theme.
1722136015.938836 WARNING root: No icon with the name RP_SETTINGS was found in the theme.

```
Fixed on [L37](https://github.com/44yu5h/rpi_control_center/commit/c8b14b4196fc5ecab51387ab90d49a32bbdcc7f4?diff=split&w=0#:~:text=button.props.icon_name%20%3D%20name.replace(%22RP_%22%2C%20%22%22).lower())

---
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3.12/site-packages/sugar3/activity/activityinstance.py", line 230, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/sugar3/activity/activityinstance.py", line 59, in create_activity_instance
    activity = constructor(handle)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/lilnga/Documents/vscode/rpi_control_center/activity.py", line 39, in __init__
    button.props.group = self.names['gpio']
                         ~~~~~~~~~~^^^^^^^^
KeyError: 'gpio'
```
Fixed on [L39](https://github.com/44yu5h/rpi_control_center/commit/c8b14b4196fc5ecab51387ab90d49a32bbdcc7f4?diff=split&w=0#:~:text=button.props.group%20%3D%20self.names%5B%27RP_GPIO%27%5D)

---
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 230, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 59, in create_activity_instance
    activity = constructor(handle)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Activities/rpi_control_center/activity.py", line 58, in __init__
    self.radiobutton_cb(None, 'gpio')
TypeError: RPiControlCenterActivity.radiobutton_cb() takes 2 positional arguments but 3 were given
```
Fixed [here](https://github.com/44yu5h/rpi_control_center/commit/076858809287f1e7fcf1c7b7918251a45dfa1d92#:~:text=self.radiobutton_cb(,button%2C%20name)%3A)

---
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 230, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 59, in create_activity_instance
    activity = constructor(handle)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Activities/rpi_control_center/activity.py", line 58, in __init__
    self.radiobutton_cb(None, 'RP_GPIO')
  File "/home/pi/Activities/rpi_control_center/activity.py", line 64, in radiobutton_cb
    self.set_canvas(globals()[button].gui)
                    ~~~~~~~~~^^^^^^^^
KeyError: 'RP_RP_GPIO'
```
Removed `button = 'RP_' + name.upper()` and replaced with `name` [here](https://github.com/44yu5h/rpi_control_center/commit/088f4ed372fa5492cb9b02b5c0806008fe6ce979#:~:text=def%20radiobutton_cb(self,button%2C%20name)%3A)

---
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 230, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 59, in create_activity_instance
    activity = constructor(handle)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Activities/rpi_control_center/activity.py", line 58, in __init__
    self.radiobutton_cb(None, 'RP_GPIO')
  File "/home/pi/Activities/rpi_control_center/activity.py", line 63, in radiobutton_cb
    self.set_canvas(globals()[name].gui)
  File "/usr/lib/python3/dist-packages/sugar3/activity/activity.py", line 698, in set_canvas
    Window.set_canvas(self, canvas)
  File "/usr/lib/python3/dist-packages/sugar3/graphics/window.py", line 249, in set_canvas
    self.__hbox.pack_start(canvas, True, True, 0)
TypeError: argument child: Expected Gtk.Widget, but got rp_tests.rp_gpio.function
```
Fixed in [L62]( https://github.com/44yu5h/rpi_control_center/commit/088f4ed372fa5492cb9b02b5c0806008fe6ce979#:~:text=self.set_canvas(globals()%5Bname%5D.gui()))

---

Lastly, there were some errors regarding CLI and GUI settings which I [fixed](https://github.com/44yu5h/rpi_control_center/commit/088f4ed372fa5492cb9b02b5c0806008fe6ce979#:~:text=%27cli%27%3A%20_,boot_cli%27%3A%200%2C) in the same commit
Also, fixed a few lines longer than 79 chars that caught my eyes

**Comment by chimosky** [comment]
> I fixed the issues you pointed out in the review. Thanks I'm sorry for not getting back to you sooner. Below are the errors and the changes I made:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/bin/sugar-activity3", line 5, in <module>
>     activityinstance.main()
>   File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 179, in main
>     module = __import__(module_name)
>              ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/pi/Activities/rpi_control_center/activity.py", line 10
>     from rp_tests.rp_audio RP_AUDIO
>                            ^^^^^^^^
> SyntaxError: invalid syntax
> ```
> 
> Fixed [L5-11](https://github.com/44yu5h/rpi_control_center/commit/088f4ed372fa5492cb9b02b5c0806008fe6ce979#:~:text=%23%20from%20gpio%20import,%2C%20name)
> 

That would've been fixed by adding the `import` part of the statement, not using `importlib`.

> Lastly, there were some errors regarding CLI and GUI settings which I [fixed](https://github.com/44yu5h/rpi_control_center/commit/088f4ed372fa5492cb9b02b5c0806008fe6ce979#:~:text=%27cli%27%3A%20_,boot_cli%27%3A%200%2C) in the same commit Also, fixed a few lines longer than 79 chars that caught my eyes

Please avoid combining various changes into a particular commit.

**Comment by 44yu5h** [comment]
> That would've been fixed by adding the `import` part of the statement, not using `importlib`.
> It's not good practice to assign names directly to globals, we also don't need this loop.

There were flake8 unused import errors and many repetitions, so I thought importing dynamically would be better. 
Thanks for pointing it out. I'll revert it

> Please avoid combining various changes into a particular commit.

My bad. Can't resist it sometimes

You can check the updated commit. Thanks

**Comment by chimosky** [comment]
> There were flake8 unused import errors and many repetitions, so I thought importing dynamically would be better.
Thanks for pointing it out. I'll revert it

You can drop any unused import, what repetition are you referring to?

> My bad. Can't resist it sometimes

I understand, when you want to make a commit, try to limit it to related changes.

> You can check the updated commit. Thanks

Took a look, I don't think the names should have `RP` as part of the names which would be visible, which is why I didn't make that change in the first place, it should just be an implementation detail that shouldn't be visible.

**Comment by 44yu5h** [comment]
@chimosky I'm sorry for leaving this hanging.

> Took a look, I don't think the names should have RP as part of the names which would be visible.

Yes. Actually, initially I was just trying to get things up and running but there were some import errors regarding packages with the same names, as far as I can remember, so I added a `rp_` at the start and then they just stuck around. Thanks for pointing out. I'll get rid of them.

> You can drop any unused import

I am talking about these, which are dynamically used later
Screenshot from 2024-08-10 19-11-42

**Comment by chimosky** [comment]
> Yes. Actually, initially I was just trying to get things up and running but there were some import errors regarding packages with the same names, as far as I can remember, so I added a rp_ at the start and then they just stuck around. Thanks for pointing out. I'll get rid of them.

As part of the module name they're fine, I was talking about how you use them in L37 of activity.py in your commit.

> I am talking about these, which are dynamically used later

We could import them later when we need them using `importlib`, like you did in your commit but they'll be in the `radiobutton_cb`.

**Comment by 44yu5h** [comment]
Okay got it! I'll make the changes soon.
Thanks!

**Comment by 44yu5h** [comment]
I made the changes you suggested. Looks good to me. Thanks for the feedbacks!
You can review if it's alright.

**Comment by chimosky** [comment]
Reviewed 65ab62c, looks good.

Had to use Github's tool to resolve the conflicts, hence 934c87e, if you've tested the changes and it works without issues then I'm fine with it.

Also made some comments.

**Comment by 44yu5h** [comment]
> Also made some comments.

Removed the redundant comments as suggested 👍🏻 

Should I merge the `fix/pr/8` branch or will you pull the changes to this PR?

**Comment by chimosky** [comment]
> > Also made some comments.
> 
> Removed the redundant comments as suggested 👍🏻
> 
> Should I merge the `fix/pr/8` branch or will you pull the changes to this PR?

You can rebase your changes here, and then merge.

**Comment by 44yu5h** [comment]
> You can rebase your changes here, and then merge.

I am not sure how to do that.

Either I can merge `fix/pr/8` branch. It has your commit history too
OR you can merge [my pr](https://github.com/sugarlabs/rpi_control_center/pull/1) that I created just now to your repo. Then I can merge this pr.

**Comment by chimosky** [comment]
Merge fix/pr/8 then, if it contains all the changes including mine.

Working on separate branches for the same issue isn't great though, you could easily push any changes you make to the branch I opened the PR in as long as you have write access to the repo.

**Comment by 44yu5h** [comment]
There were conflicts so had to rebase. Merged here #10 

Thanks again! 👍🏻 
Closing this now

**Comment by chimosky** [comment]
For future reference, avoid referencing Github issue numbers in commit messages as only GH recognizes it and git doesn't, so if someone were to view your commit message in git they wouldn't know what you're referring to.

**Pull request closed without merging**
